server:
  port: 5001
spring:
  application:
    name: management-platform-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaofengjiao0/management-platform-config.git

